sudo: required

language: java

jdk: oraclejdk8

services:
  - docker

env:
  matrix:
    - ES_VERSION=2.1.1

before_script:
  - cd testenv
  - ./setup_testenv.sh
  - ./start_testenv.sh
  - cd ../
  - sleep 15

script: ./gradlew check